project:
  type: math-book
  resources: assets

book:
  title: "Math Book Template" # TODO: change
  author: "Felix Benning" # TODO: change
  date: last-modified
  site-url: https://unassuming.page/math-book # TODO: change
  # favicon: logo.png
  repo-url: https://github.com/FelixBenning/math-book # TODO: change
  chapters:
    - index.qmd
    - usage.qmd
    - extensions.qmd
    - details.qmd
    - references.qmd

bibliography: references.bib

format:
  math-book-html:
    theme:
      - cosmo # select a theme from (https://bootswatch.com/)
      - brand # use a _brand.yml file to customize (https://posit-dev.github.io/brand-yml/)
  math-book-pdf:
    keep-tex: false # set to true to obtain tex files
    cite-method: biblatex # or natbib
    pdf-engine: pdflatex # xelatex # alternatives: pdflatex (old, most common) or lualatex

editor:
  render-on-save: true

comments:
  hypothesis: true # allow comments (https://web.hypothes.is/)



